### ISSUE TITLE
bug: it tooks me a bad server

### ISSUE THREAD

**Issue by willemijns** [chr15m/twiiit.com#1]
Hello he tooks me a bad server:

https://nitter.weaponizedhumiliation.com/

Why your script considers it as OK ???  ping is not enough ;)

**Comment by chr15m** [comment]
@willemijns it could be a bug. The script checks each server every 5 minutes. It's possible that the server responded with "OK" and then became unavailable or overloaded during the 5 minutes.

**Comment by willemijns** [comment]
No. This server was down since X weeks. - i - moved myself this server to the bad nitter list 
he answers to ping.

---------------------

Secure Connection Failed
An error occurred during a connection to nitter.weaponizedhumiliation.com. PR_CONNECT_RESET_ERROR

... differs from ...

Hmm. We’re having trouble finding that site.
We can’t connect to the server at www.foo-foo-foo-foo-foo-foo.com.




  Sébastien WILLEMIJNS

**Comment by chr15m** [comment]
@willemijns yes you're right, that's a bug.
