### ISSUE TITLE
Feature Request: Better handling of RSS feeds

### ISSUE THREAD

**Issue by burrhole** [chr15m/twiiit.com#2]
Fist off, apologies if this is a bit outside of scope for this project.
As it currently functions, pointing an RSS reader to twiiit.com/(user)/rss will find an instance and download the RSS feed for a given profile from that instance, and then on the next request may pull the feed from a separate instance. This causes a bit of an issue with RSS readers such as tt-rss / liferea, where every time the feed is refreshed, a completely new, duplicate feed is pulled in to the reader, causing many duplicate "new" entries for the same feed where one would expect it to only pull in new tweets. 
I'm not exactly sure what a good fix for this would look like; possibly have an "internal" rss feed/nitter instance that then proxies to posts on other nitter instances?

This is an illustration of the current behavior I'm referring to for https://twiiit.com/SoloKeysSec/rss in liferea: [https://imgur.com/0XD6DCp](url)

Thank you for your work and your time!

**Comment by chr15m** [comment]
@burrhole understood. At the moment the proxy can take a lot of traffic because it simply returns HTTP redirects. If it is modified to actually proxy the requests it would be more like Nitter itself and would start to suffer from the same outages. Not sure how to solve the problem you are facing without introducing outage risk.

**Comment by hdhoang** [comment]
can nitter make a guid for items based on canonical twitter url? that may help with most aggregators, and twiiit stays stateless

thanks for trying that out

**Comment by chr15m** [comment]
@hdhoang if you want to implement this you should submit a PR to Nitter itself.

**Comment by mrdan** [comment]
For anyone else who happens upon here, there's an issue for this concept with nitter already https://github.com/zedeus/nitter/issues/447

**Comment by somedevreally** [comment]
doesn't look like nitter will implement it
