### ISSUE TITLE
please add mobile.twiiit.com subdomain

### ISSUE THREAD

**Issue by hdhoang** [chr15m/twiiit.com#5]
I don't use nitter instances exclusively, but sometimes manually edit url bar to `twiiit.com` instead. From `mobile.twitter.com`, it'd really help if just editing a few characters can work. Thanks in advance!

I'd understand if you don't like this :)

**Comment by chr15m** [comment]
Hi @hdhoang - thanks for the feature request but it sounds like this is outside of scope for twiiit.com. You could make a javascript bookmark to do this for you or create an extension.
