### ISSUE TITLE
Redirection to discontinued server

### ISSUE THREAD

**Issue by delaguilaluis** [chr15m/twiiit.com#9]
When querying a URL, I got redirected to a server listed under the "Discontinued" server list (https://nitter.ca).
I was able to reproduce with curl:

```shell
~ % curl https://twiiit.com/RLEsports
Found. Redirecting to https://nitter.ca/RLEsports
```

**Comment by chr15m** [comment]
@delaguilaluis I've resorted to a workaround to reboot the server nightly as it kept getting stuck when trying to keep the list updated. That server is gone from the internal list now. Let me know if you see it happen again, and thanks for reporting. :pray:
